### ISSUE TITLE
403 forbidden error and connection close while running start_listener.sh

### ISSUE THREAD

**Issue by shravan26** [zenetio/ai-4-clinical-workflow#1]
Hey I'm a little new to this but why does it say 403 forbidden and connection close when i try to run start_listener.sh ? However I try looking there isn't any authentication that is required but it still says forbidden. Why am I facing this ? Any help would be appreciated 
P.S. Sorry if this is a stupid question or if i need prior knowledge to something else in order to understand this. If that is the issue please lead me to the right resources.

**Comment by zenetio** [comment]
Hi @Shravan,
The error status response code indicates that the server understands the request but refuses to authorize it.
You will neet to work with your environment to find out where is the problem.
You can check in the link below some suggestions like clean cache or cookies
https://www.lifewire.com/403-forbidden-error-explained-2617989
[https://www.lifewire.com/thmb/AnB9G4kziZwR2HVuBXirOtvBm9g=/1500x1000/filters:fill(auto,1)/403-forbidden-error-explained-2617989-2d79b84333b84a669430fd18f60dc9c9.png]<https://www.lifewire.com/403-forbidden-error-explained-2617989>
How to Fix a 403 Forbidden Error - Lifewire<https://www.lifewire.com/403-forbidden-error-explained-2617989>
Tim Fisher has more than 30 years' of professional technology experience. He's been writing about tech for more than two decades and serves as the VP and General Manager of Lifewire.
www.lifewire.com

________________________________
De: Shravan Venkatesh ***@***.***>
Enviado: sexta-feira, 12 de novembro de 2021 18:53
Para: zenetio/ai-4-clinical-workflow ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [zenetio/ai-4-clinical-workflow] 403 forbidden error and connection close while running start_listener.sh (Issue #1)


Hey I'm a little new to this but why does it say 403 forbidden and connection close when i try to run start_listener.sh ? However I try looking there isn't any authentication that is required but it still says forbidden. Why am I facing this ? Any help would be appreciated
P.S. Sorry if this is a stupid question or if i need prior knowledge to something else in order to understand this. If that is the issue please lead me to the right resources.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzenetio%2Fai-4-clinical-workflow%2Fissues%2F1&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404751575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gWMQBvjRTKjTyvIQ5v3AeUHiuCIGxYsylHpKupU1aGE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAENGIPSVABH2B26A3XBRMTULVPELANCNFSM5H5PDRRQ&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404751575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qDToKvrdPQefjacnv%2Fvml1rxGbun5m%2F4Z38VY%2FdkLUM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404761575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZkVfSkOvhFOZkmWAeTQhrMYl%2BJQfBTVIS7uU4YygM%2FA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404771564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qlBySXmwNFUC%2BzXQh%2FcWiWj0KG2B1T4hj66BklEwFlg%3D&reserved=0>.

**Comment by zenetio** [comment]
Another suggestion, as start_listener.sh is a script, you can try to run each command by hand.
Keep learning!
________________________________
De: Carlos Roberto ***@***.***>
Enviado: sexta-feira, 12 de novembro de 2021 20:50
Para: zenetio/ai-4-clinical-workflow ***@***.***>
Assunto: RE: [zenetio/ai-4-clinical-workflow] 403 forbidden error and connection close while running start_listener.sh (Issue #1)

Hi @Shravan,
The error status response code indicates that the server understands the request but refuses to authorize it.
You will neet to work with your environment to find out where is the problem.
You can check in the link below some suggestions like clean cache or cookies
https://www.lifewire.com/403-forbidden-error-explained-2617989
[https://www.lifewire.com/thmb/AnB9G4kziZwR2HVuBXirOtvBm9g=/1500x1000/filters:fill(auto,1)/403-forbidden-error-explained-2617989-2d79b84333b84a669430fd18f60dc9c9.png]<https://www.lifewire.com/403-forbidden-error-explained-2617989>
How to Fix a 403 Forbidden Error - Lifewire<https://www.lifewire.com/403-forbidden-error-explained-2617989>
Tim Fisher has more than 30 years' of professional technology experience. He's been writing about tech for more than two decades and serves as the VP and General Manager of Lifewire.
www.lifewire.com

________________________________
De: Shravan Venkatesh ***@***.***>
Enviado: sexta-feira, 12 de novembro de 2021 18:53
Para: zenetio/ai-4-clinical-workflow ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [zenetio/ai-4-clinical-workflow] 403 forbidden error and connection close while running start_listener.sh (Issue #1)


Hey I'm a little new to this but why does it say 403 forbidden and connection close when i try to run start_listener.sh ? However I try looking there isn't any authentication that is required but it still says forbidden. Why am I facing this ? Any help would be appreciated
P.S. Sorry if this is a stupid question or if i need prior knowledge to something else in order to understand this. If that is the issue please lead me to the right resources.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzenetio%2Fai-4-clinical-workflow%2Fissues%2F1&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404751575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gWMQBvjRTKjTyvIQ5v3AeUHiuCIGxYsylHpKupU1aGE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAENGIPSVABH2B26A3XBRMTULVPELANCNFSM5H5PDRRQ&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404751575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qDToKvrdPQefjacnv%2Fvml1rxGbun5m%2F4Z38VY%2FdkLUM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404761575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZkVfSkOvhFOZkmWAeTQhrMYl%2BJQfBTVIS7uU4YygM%2FA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2f615d36d93c47cd698008d9a60dc8d2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637723400404771564%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qlBySXmwNFUC%2BzXQh%2FcWiWj0KG2B1T4hj66BklEwFlg%3D&reserved=0>.
